[package]
name = "mbtunnel-win-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
chacha20 = "0.10.0"
chrono = { version = "0.4.44", features= ["serde"] }
eframe = "0.34.1"
egui_extras = "0.34.1"
getrandom = "0.4.2"
regex = "1.12.3"
rfd = "0.17.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
ureq = "3.3.0"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
zstd = "0.13.3"
tokio = "1.52.2"
reqwest = { version = "0.13.3", default-features = false, features = ["http3", "rustls"] }
wstunnel = { git = "https://github.com/erebe/wstunnel", tag = "v10.5.0", package = "wstunnel" }

[profile.release]
strip = true
lto = "none"
opt-level = "z"
codegen-units = 1


